stages:
  - build

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  CHECK_GIT: git diff origin/master --name-only

before_script:
  # Enable GitLab registry
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${REGISTRY}

.build_template: &build_definition
  stage: build
  tags:
    - deploy_test
  interruptible: true
  script:
    - >
      if  [ ${CI_COMMIT_REF_NAME} = master ] || \
          ${CHECK_GIT} | grep "^versions/${OS}_${DIST}_${VER}$" || \
          ${CHECK_GIT} | grep "^dockerfiles/${OS}_${DIST}_${DOCKERFILE_NAME_SUFFIX}$" || \
          ${CHECK_GIT} | grep "^files/" || \
          ${CHECK_GIT} | grep "^.gitlab-ci.yml$" || \
          ${CHECK_GIT} | grep "^.gitlab.mk$"
      then
        make -f .gitlab.mk build
      fi;

# ##############
# ALPINE 3.5/3.9
# ##############

# Tarantool branch 1.10

'alpine 3.5 1.10.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.0'
    VER: '1.10.0'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5101

'alpine 3.5 1.10.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.1'
    VER: '1.10.1'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5101

'alpine 3.5 1.10.2':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.2'
    VER: '1.10.2'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5102

'alpine 3.5 1.10.3':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.3'
    VER: '1.10.3'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5103

'alpine 3.9 1.10.4':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.4'
    VER: '1.10.4'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5104

'alpine 3.9 1.10.5':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.5'
    VER: '1.10.5'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5105

'alpine 3.9 1.10.6':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.6'
    VER: '1.10.6'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5106

'alpine 3.9 1.x':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1'
    VER: '1.x'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5100

# Tarantool branch 2.1

'alpine 3.5 2.1.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.0'
    VER: '2.1.0'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5211

'alpine 3.5 2.1.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.1'
    VER: '2.1.1'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5211

'alpine 3.5 2.1.2':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.2'
    VER: '2.1.2'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5212

'alpine 3.9 2.1.3':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.1.3'
    VER: '2.1.3'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 5213

'alpine 3.9 2.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.1'
    VER: '2.1'
    DOCKERFILE_NAME_SUFFIX: '2.2'
    PORT: 5210

# Tarantool branch 2.2

'alpine 3.5 2.2.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.2.0'
    VER: '2.2.0'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5220

'alpine 3.5 2.2.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.2.1'
    VER: '2.2.1'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5221

'alpine 3.9 2.2.2':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2.2'
    VER: '2.2.2'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5222

'alpine 3.9 2.2.3':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2.3'
    VER: '2.2.3'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5223

'alpine 3.9 2.2':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2'
    VER: '2.2'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5220

# Tarantool branch 2.3

'alpine 3.5 2.3.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.3.0'
    VER: '2.3.0'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5231

'alpine 3.9 2.3.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3.1'
    VER: '2.3.1'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5231

'alpine 3.9 2.3.2':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3.2'
    VER: '2.3.2'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5231

'alpine 3.9 2.3':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3'
    VER: '2.3'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5230

# Tarantool branch 2.4

'alpine 3.9 2.4.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.0'
    VER: '2.4.0'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5241

'alpine 3.9 2.4.1':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.1'
    VER: '2.4.1'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5241

'alpine 3.9 2.4':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4'
    VER: '2.4'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5240

# Tarantool branch master

'alpine 3.9 2.5.0':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5.0'
    VER: '2.5.0'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5251

'alpine 3.9 2.x':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2'
    VER: '2.x'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 5200
    TAG_LATEST: 'latest'

# ########
# CentOS 7
# ########

# Tarantool branch 1.10

'centos 7 1.x':
  <<: *build_definition
  variables:
    OS: 'centos'
    DIST: '7'
    TAG: '1.x-centos7'
    VER: '1.x'
    DOCKERFILE_NAME_SUFFIX: '1.x'
    PORT: 7100

# Tarantool branch master

'centos 7 2.x':
  <<: *build_definition
  variables:
    OS: 'centos'
    DIST: '7'
    TAG: '2.x-centos7'
    VER: '2.x'
    DOCKERFILE_NAME_SUFFIX: '2.x'
    PORT: 7200
