stages:
  - build

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  CHECK_GIT: git diff origin/master --name-only

before_script:
  # Enable GitLab registry
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${REGISTRY}

.build_template: &build_definition
  stage: build
  tags:
    - deploy_test
  interruptible: true
  script:
    - >
      if  [ ${CI_COMMIT_REF_NAME} = master ] || \
          ${CHECK_GIT} | grep "^versions/${OS}_${DIST}_${VER}$" || \
          ${CHECK_GIT} | grep "^dockerfiles/${OS}_${DIST}_${DOCKERFILE_NAME_SUFFIX}$" || \
          ${CHECK_GIT} | grep "^files/" || \
          ${CHECK_GIT} | grep "^.gitlab-ci.yml$" || \
          ${CHECK_GIT} | grep "^.gitlab.mk$"
      then
        make -f .gitlab.mk build
      fi;

# ##############
# ALPINE 3.5/3.9
# ##############

# Tarantool branch 1.10

'alpine 3.5 1.10.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.0'
    VER: '1.10.0'
    PORT: 5101
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 1.10.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.1'
    VER: '1.10.1'
    PORT: 5101
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 1.10.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.2'
    VER: '1.10.2'
    PORT: 5102
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 1.10.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '1.10.3'
    VER: '1.10.3'
    PORT: 5103
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 1.10.4':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.4'
    VER: '1.10.4'
    PORT: 5104
    ROCKS_INSTALLER: 'luarocks'
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 1.10.5':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.5'
    VER: '1.10.5'
    PORT: 5105
    ROCKS_INSTALLER: 'luarocks'
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 1.10.6':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.6'
    VER: '1.10.6'
    PORT: 5106
    ROCKS_INSTALLER: 'luarocks'
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 1.10.7':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.7'
    VER: '1.10.7'
    PORT: 5107
    ROCKS_INSTALLER: 'luarocks'

'alpine 3.9 1.10.8':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.8'
    VER: '1.10.8'
    PORT: 5108
    ROCKS_INSTALLER: 'luarocks'

'alpine 3.9 1.10.9':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.9'
    VER: '1.10.9'
    PORT: 5109
    ROCKS_INSTALLER: 'luarocks'

'alpine 3.9 1.10.10':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1.10.10'
    VER: '1.10.10'
    PORT: 5110
    ROCKS_INSTALLER: 'luarocks'

'alpine 3.9 1.x':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '1'
    VER: '1.x'
    PORT: 5100
    ROCKS_INSTALLER: 'luarocks'

# Tarantool branch 2.1

'alpine 3.5 2.1.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.0'
    VER: '2.1.0'
    PORT: 5211
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 2.1.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.1'
    VER: '2.1.1'
    PORT: 5211
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 2.1.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.1.2'
    VER: '2.1.2'
    PORT: 5212
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 2.1.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.1.3'
    VER: '2.1.3'
    PORT: 5213
    ROCKS_INSTALLER: 'luarocks'
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.9 2.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.1'
    VER: '2.1'
    PORT: 5210
    ROCKS_INSTALLER: 'luarocks'
    ENABLE_BUNDLED_LIBYAML: 'OFF'

# Tarantool branch 2.2

'alpine 3.5 2.2.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.2.0'
    VER: '2.2.0'
    PORT: 5220
    ENABLE_BUNDLED_LIBYAML: 'OFF'

'alpine 3.5 2.2.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.2.1'
    VER: '2.2.1'
    PORT: 5221

'alpine 3.9 2.2.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2.2'
    VER: '2.2.2'
    PORT: 5222

'alpine 3.9 2.2.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2.3'
    VER: '2.2.3'
    PORT: 5223

'alpine 3.9 2.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.2'
    VER: '2.2'
    PORT: 5220

# Tarantool branch 2.3

'alpine 3.5 2.3.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.5'
    TAG: '2.3.0'
    VER: '2.3.0'
    PORT: 5231

'alpine 3.9 2.3.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3.1'
    VER: '2.3.1'
    PORT: 5231

'alpine 3.9 2.3.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3.2'
    VER: '2.3.2'
    PORT: 5231

'alpine 3.9 2.3.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3.3'
    VER: '2.3.3'
    PORT: 5233

'alpine 3.9 2.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.3'
    VER: '2.3'
    PORT: 5230

# Tarantool branch 2.4

'alpine 3.9 2.4.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.0'
    VER: '2.4.0'
    PORT: 5241

'alpine 3.9 2.4.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.1'
    VER: '2.4.1'
    PORT: 5241

'alpine 3.9 2.4.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.2'
    VER: '2.4.2'
    PORT: 5242

'alpine 3.9 2.4.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4.3'
    VER: '2.4.3'
    PORT: 5243

'alpine 3.9 2.4':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.4'
    VER: '2.4'
    PORT: 5240

# Tarantool branch 2.5

'alpine 3.9 2.5.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5.0'
    VER: '2.5.0'
    PORT: 5251

'alpine 3.9 2.5.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5.1'
    VER: '2.5.1'
    PORT: 5252

'alpine 3.9 2.5.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5.2'
    VER: '2.5.2'
    PORT: 5253

'alpine 3.9 2.5.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5.3'
    VER: '2.5.3'
    PORT: 5254

'alpine 3.9 2.5':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.5'
    VER: '2.5'
    PORT: 5250

# Tarantool branch 2.6

'alpine 3.9 2.6.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.6.0'
    VER: '2.6.0'
    PORT: 5260

'alpine 3.9 2.6.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.6.1'
    VER: '2.6.1'
    PORT: 5261

'alpine 3.9 2.6.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.6.2'
    VER: '2.6.2'
    PORT: 5262

'alpine 3.9 2.6.3':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.6.3'
    VER: '2.6.3'
    PORT: 5263

'alpine 3.9 2.6':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.6'
    VER: '2.6'
    PORT: 5269

# Tarantool branch 2.7

'alpine 3.9 2.7.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.7.0'
    VER: '2.7.0'
    PORT: 5270

'alpine 3.9 2.7.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.7.1'
    VER: '2.7.1'
    PORT: 5271

'alpine 3.9 2.7.2':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.7.2'
    VER: '2.7.2'
    PORT: 5272

'alpine 3.9 2.7':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.7'
    VER: '2.7'
    PORT: 5279

# Tarantool branch 2.8

'alpine 3.9 2.8.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.8.0'
    VER: '2.8.0'
    PORT: 5270

'alpine 3.9 2.8.1':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.8.1'
    VER: '2.8.1'
    PORT: 5281

'alpine 3.9 2.8':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.8'
    VER: '2.8'
    PORT: 5289

# Tarantool branch master

'alpine 3.9 2.9.0':
  <<: *build_definition
  when: manual
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2.9.0'
    VER: '2.9.0'
    PORT: 5290

'alpine 3.9 2.x':
  <<: *build_definition
  variables:
    OS: 'alpine'
    DIST: '3.9'
    TAG: '2'
    VER: '2.x'
    PORT: 5200
    TAG_LATEST: 'latest'

# ########
# CentOS 7
# ########

# Tarantool branch 1.10

'centos 7 1.x':
  <<: *build_definition
  variables:
    OS: 'centos'
    DIST: '7'
    TAG: '1.x-centos7'
    VER: '1.x'
    PORT: 7100

# Tarantool branch master

'centos 7 2.x':
  <<: *build_definition
  variables:
    OS: 'centos'
    DIST: '7'
    TAG: '2.x-centos7'
    VER: '2.x'
    PORT: 7200
